apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    spec:
      containers:
        - name: demo
          image: demo:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: key1
              value: value1
            - name: key2
              value: value2
